//generated by start.spring.io
package fr.formation.webflix;

import fr.formation.webflix.entities.UserEntity;
import fr.formation.webflix.enums.Gender;
import fr.formation.webflix.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.Calendar;

@SpringBootApplication(exclude={SecurityAutoConfiguration.class})// permet exclure l'application securité
public class WebflixApplication  extends SpringBootServletInitializer {
@Autowired
private UserService userService;
	public static void main(String[] args) {

		SpringApplication.run(WebflixApplication.class, args);
		}

		@GetMapping("/")
		public String getHello(){
		return  "Hello moi";
		}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
		return builder.sources(WebflixApplication.class);
	}

	//	@Bean
//	public void saveUser(){
//		UserEntity user = new UserEntity();
//		user.setEmail("treza88@hotmail.fr");
//		user.setPassword("azer");
//		user.setFirstname("RV");
//		user.setLastname("Thom");
//		user.setCountry("France");
//		user.setGender(Gender.MR);
//		user.setDateCreated(Calendar.getInstance());
//
//		System.out.println(user);
//
//		 userService.save(user);
//	}

//@Bean
//	public void deleteAllUser(){
//		userService.deleteAll();
//}



}
